spring:
  main:
    banner-mode: OFF
    log-startup-info: true
    register-shutdown-hook: true
    web-application-type: reactive
  application:
    name: "Parking Lot"
  mustache:
    check-template-location: false


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      cache:
        time-to-live: 5m
      enabled: true

logging:
  level:
    javasd.shaded.com.twilio.cartographer: INFO
